controller_manager:
  ros__parameters:
    update_rate: 100
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_position_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    velocity_controllers:
      type: velocity_controllers/JointGroupVelocityController