controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controller:
      type: effort_controllers/JointGroupEffortController
    
    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    
    position_controller:
      type: position_controllers/JointGroupPositionController

effort_controller:
  ros__parameters:
    joints: 
      - hip_jointL
      - knee_jointL
      - virtualhip_jointL
      - wheel_jointL
      - hip_jointR
      - knee_jointR
      - virtualhip_jointR
      - wheel_jointR

velocity_controller:
  ros__parameters:
    joints: 
      - wheel_jointL
      - wheel_jointR

position_controller:
  ros__parameters:
    joints:
      - hip_jointL
      - knee_jointL
      - virtualhip_jointL
      - hip_jointR
      - knee_jointR
      - virtualhip_jointR

