controller_manager:
  ros__parameters:
    update_rate: 2000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controller:
      type: effort_controllers/JointGroupEffortController
    
    position_controller:
      type: position_controllers/JointGroupPositionController

effort_controller:
  ros__parameters:
    joints: 
      - wheel_jointL
      - wheel_jointR
      - knee_jointL
      - virtualhip_jointL
      - knee_jointR
      - virtualhip_jointR

